spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev     #开发环境
  application:
    name: seckill-config-dev
---
spring:
  profiles: test   #测试环境
  application:
    name: seckill-config-test
---
spring:
  profiles: test   #生产环境
  application:
    name: seckill-config-prod