spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: seckill-config-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: seckill-config-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
